//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBooking.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Booking_number { get; set; }
        public string Room_code { get; set; }
        public int Client_code { get; set; }
        public string TypeOfFood { get; set; }
        public int Payment_number { get; set; }
        public System.DateTime DateOfBooking { get; set; }
        public System.DateTime Departuree { get; set; }
        public System.DateTime Arrivall { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Pay Pay { get; set; }
        public virtual Room Room { get; set; }
        public virtual TypeOfFood TypeOfFood1 { get; set; }
    }
}
