//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBooking.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay
    {
        public int Payment_number { get; set; }
        public System.DateTime DateOfPay { get; set; }
        public int Payer { get; set; }
        public string Card_number { get; set; }
        public decimal Summ { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
