//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBooking.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public string Room_code { get; set; }
        public string Code_category { get; set; }
        public string Repair { get; set; }
        public string Booking { get; set; }
        public string Free { get; set; }
    
        public virtual CategoryOfRoom CategoryOfRoom { get; set; }
    }
}
