//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBooking.Model
{
    using System;
    
    public partial class SelectBooking
    {
        public int Booking_number { get; set; }
        public string Room_code { get; set; }
        public string Full_name { get; set; }
        public string Type_name { get; set; }
        public int Payment_number { get; set; }
        public System.DateTime DateOfBooking { get; set; }
        public System.DateTime Arrivall { get; set; }
        public System.DateTime Departuree { get; set; }
        public decimal Summ { get; set; }
    }
}
