//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBooking.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeOfFood
    {
        public string Type_code { get; set; }
        public string Type_name { get; set; }
        public decimal Summa { get; set; }
    }
}
