//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBooking.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public int Worker_code { get; set; }
        public string Full_name { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string Position { get; set; }
        public decimal Salary { get; set; }
    }
}
